package me.alexn.neotech.infrastructure.configuration

import me.alexn.neotech.application.domain.CountryCode

val countryCodesFallback = listOf(
    CountryCode(code = "+93", country = "Afghanistan"),
    CountryCode(code = "+5993", country = "Caribbean Netherlands"),
    CountryCode(code = "+5994", country = "Caribbean Netherlands"),
    CountryCode(code = "+5997", country = "Caribbean Netherlands"),
    CountryCode(code = "+35818", country = "Åland Islands"),
    CountryCode(code = "+355", country = "Albania"),
    CountryCode(code = "+213", country = "Algeria"),
    CountryCode(code = "+1684", country = "American Samoa"),
    CountryCode(code = "+376", country = "Andorra"),
    CountryCode(code = "+244", country = "Angola"),
    CountryCode(code = "+1264", country = "Anguilla"),
    CountryCode(code = "+1268", country = "Antigua and Barbuda"),
    CountryCode(code = "+54", country = "Argentina"),
    CountryCode(code = "+374", country = "Armenia"),
    CountryCode(code = "+297", country = "Aruba"),
    CountryCode(code = "+247", country = "Ascension"),
    CountryCode(code = "+61", country = "Australia"),
    CountryCode(code = "+6721", country = "Australian Antarctic Territory"),
    CountryCode(code = "+672", country = "Australian External Territories"),
    CountryCode(code = "+43", country = "Austria"),
    CountryCode(code = "+994", country = "Azerbaijan"),
    CountryCode(code = "+1242", country = "Bahamas"),
    CountryCode(code = "+973", country = "Bahrain"),
    CountryCode(code = "+880", country = "Bangladesh"),
    CountryCode(code = "+1246", country = "Barbados"),
    CountryCode(code = "+1268", country = "Barbuda"),
    CountryCode(code = "+375", country = "Belarus"),
    CountryCode(code = "+32", country = "Belgium"),
    CountryCode(code = "+501", country = "Belize"),
    CountryCode(code = "+229", country = "Benin"),
    CountryCode(code = "+1441", country = "Bermuda"),
    CountryCode(code = "+975", country = "Bhutan"),
    CountryCode(code = "+591", country = "Bolivia"),
    CountryCode(code = "+5997", country = "Bonaire"),
    CountryCode(code = "+387", country = "Bosnia and Herzegovina"),
    CountryCode(code = "+267", country = "Botswana"),
    CountryCode(code = "+55", country = "Brazil"),
    CountryCode(code = "+246", country = "British Indian Ocean Territory"),
    CountryCode(code = "+1284", country = "British Virgin Islands"),
    CountryCode(code = "+673", country = "Brunei Darussalam"),
    CountryCode(code = "+359", country = "Bulgaria"),
    CountryCode(code = "+226", country = "Burkina Faso"),
    CountryCode(code = "+257", country = "Burundi"),
    CountryCode(code = "+238", country = "Cape Verde"),
    CountryCode(code = "+855", country = "Cambodia"),
    CountryCode(code = "+237", country = "Cameroon"),
    CountryCode(code = "+1", country = "Canada"),
    CountryCode(code = "+5993", country = "Caribbean Netherlands"),
    CountryCode(code = "+5994", country = "Caribbean Netherlands"),
    CountryCode(code = "+5997", country = "Caribbean Netherlands"),
    CountryCode(code = "+1345", country = "Cayman Islands"),
    CountryCode(code = "+236", country = "Central African Republic"),
    CountryCode(code = "+235", country = "Chad"),
    CountryCode(code = "+64", country = "Chatham Island, New Zealand"),
    CountryCode(code = "+56", country = "Chile"),
    CountryCode(code = "+86", country = "China"),
    CountryCode(code = "+6189164", country = "Christmas Island"),
    CountryCode(code = "+6189162", country = "Cocos (Keeling) Islands"),
    CountryCode(code = "+57", country = "Colombia"),
    CountryCode(code = "+269", country = "Comoros"),
    CountryCode(code = "+242", country = "Congo"),
    CountryCode(code = "+243", country = "Congo, Democratic Republic of the (Zaire)"),
    CountryCode(code = "+682", country = "Cook Islands"),
    CountryCode(code = "+506", country = "Costa Rica"),
    CountryCode(code = "+225", country = "Ivory Coast"),
    CountryCode(code = "+385", country = "Croatia"),
    CountryCode(code = "+53", country = "Cuba"),
    CountryCode(code = "+5999", country = "Curaçao"),
    CountryCode(code = "+357", country = "Cyprus"),
    CountryCode(code = "+420", country = "Czech Republic"),
    CountryCode(code = "+45", country = "Denmark"),
    CountryCode(code = "+246", country = "Diego Garcia"),
    CountryCode(code = "+253", country = "Djibouti"),
    CountryCode(code = "+1767", country = "Dominica"),
    CountryCode(code = "+1809", country = "Dominican Republic"),
    CountryCode(code = "+1829", country = "Dominican Republic"),
    CountryCode(code = "+1849", country = "Dominican Republic"),
    CountryCode(code = "+56", country = "Easter Island"),
    CountryCode(code = "+593", country = "Ecuador"),
    CountryCode(code = "+20", country = "Egypt"),
    CountryCode(code = "+503", country = "El Salvador"),
    CountryCode(code = "+8812", country = "Ellipso (Mobile Satellite service)"),
    CountryCode(code = "+8813", country = "Ellipso (Mobile Satellite service)"),
    CountryCode(code = "+88213", country = "EMSAT (Mobile Satellite service)"),
    CountryCode(code = "+240", country = "Equatorial Guinea"),
    CountryCode(code = "+291", country = "Eritrea"),
    CountryCode(code = "+372", country = "Estonia"),
    CountryCode(code = "+268", country = "eSwatini"),
    CountryCode(code = "+251", country = "Ethiopia"),
    CountryCode(code = "+500", country = "Falkland Islands"),
    CountryCode(code = "+298", country = "Faroe Islands"),
    CountryCode(code = "+679", country = "Fiji"),
    CountryCode(code = "+358", country = "Finland"),
    CountryCode(code = "+33", country = "France"),
    CountryCode(code = "+596", country = "French Antilles"),
    CountryCode(code = "+594", country = "French Guiana"),
    CountryCode(code = "+689", country = "French Polynesia"),
    CountryCode(code = "+241", country = "Gabon"),
    CountryCode(code = "+220", country = "Gambia"),
    CountryCode(code = "+995", country = "Georgia"),
    CountryCode(code = "+49", country = "Germany"),
    CountryCode(code = "+233", country = "Ghana"),
    CountryCode(code = "+350", country = "Gibraltar"),
    CountryCode(code = "+881", country = "Global Mobile Satellite System (GMSS)"),
    CountryCode(code = "+8818", country = "Globalstar (Mobile Satellite Service)"),
    CountryCode(code = "+8819", country = "Globalstar (Mobile Satellite Service)"),
    CountryCode(code = "+30", country = "Greece"),
    CountryCode(code = "+299", country = "Greenland"),
    CountryCode(code = "+1473", country = "Grenada"),
    CountryCode(code = "+590", country = "Guadeloupe"),
    CountryCode(code = "+1671", country = "Guam"),
    CountryCode(code = "+502", country = "Guatemala"),
    CountryCode(code = "+441481", country = "Guernsey"),
    CountryCode(code = "+447781", country = "Guernsey"),
    CountryCode(code = "+447839", country = "Guernsey"),
    CountryCode(code = "+447911", country = "Guernsey"),
    CountryCode(code = "+224", country = "Guinea"),
    CountryCode(code = "+245", country = "Guinea-Bissau"),
    CountryCode(code = "+592", country = "Guyana"),
    CountryCode(code = "+509", country = "Haiti"),
    CountryCode(code = "+504", country = "Honduras"),
    CountryCode(code = "+852", country = "Hong Kong"),
    CountryCode(code = "+36", country = "Hungary"),
    CountryCode(code = "+354", country = "Iceland"),
    CountryCode(code = "+8810", country = "ICO Global (Mobile Satellite Service)"),
    CountryCode(code = "+8811", country = "ICO Global (Mobile Satellite Service)"),
    CountryCode(code = "+91", country = "India"),
    CountryCode(code = "+62", country = "Indonesia"),
    CountryCode(code = "+870", country = "Inmarsat SNAC"),
    CountryCode(code = "+800", country = "International Freephone Service (UIFN)"),
    CountryCode(code = "+882", country = "International Networks"),
    CountryCode(code = "+883", country = "International Networks"),
    CountryCode(code = "+979", country = "International Premium Rate Service"),
    CountryCode(code = "+808", country = "International Shared Cost Service (ISCS)"),
    CountryCode(code = "+98", country = "Iran"),
    CountryCode(code = "+964", country = "Iraq"),
    CountryCode(code = "+353", country = "Ireland"),
    CountryCode(code = "+8816", country = "Iridium (Mobile Satellite service)"),
    CountryCode(code = "+8817", country = "Iridium (Mobile Satellite service)"),
    CountryCode(code = "+441624", country = "Isle of Man"),
    CountryCode(code = "+447524", country = "Isle of Man"),
    CountryCode(code = "+447624", country = "Isle of Man"),
    CountryCode(code = "+447924", country = "Isle of Man"),
    CountryCode(code = "+972", country = "Israel"),
    CountryCode(code = "+39", country = "Italy"),
    CountryCode(code = "+1876", country = "Jamaica"),
    CountryCode(code = "+4779", country = "Jan Mayen"),
    CountryCode(code = "+81", country = "Japan"),
    CountryCode(code = "+441534", country = "Jersey"),
    CountryCode(code = "+962", country = "Jordan"),
    CountryCode(code = "+76", country = "Kazakhstan"),
    CountryCode(code = "+77", country = "Kazakhstan"),
    CountryCode(code = "+254", country = "Kenya"),
    CountryCode(code = "+686", country = "Kiribati"),
    CountryCode(code = "+850", country = "Korea, North"),
    CountryCode(code = "+82", country = "Korea, South"),
    CountryCode(code = "+383", country = "Kosovo"),
    CountryCode(code = "+965", country = "Kuwait"),
    CountryCode(code = "+996", country = "Kyrgyzstan"),
    CountryCode(code = "+856", country = "Laos"),
    CountryCode(code = "+371", country = "Latvia"),
    CountryCode(code = "+961", country = "Lebanon"),
    CountryCode(code = "+266", country = "Lesotho"),
    CountryCode(code = "+231", country = "Liberia"),
    CountryCode(code = "+218", country = "Libya"),
    CountryCode(code = "+423", country = "Liechtenstein"),
    CountryCode(code = "+370", country = "Lithuania"),
    CountryCode(code = "+352", country = "Luxembourg"),
    CountryCode(code = "+853", country = "Macau"),
    CountryCode(code = "+261", country = "Madagascar"),
    CountryCode(code = "+265", country = "Malawi"),
    CountryCode(code = "+60", country = "Malaysia"),
    CountryCode(code = "+960", country = "Maldives"),
    CountryCode(code = "+223", country = "Mali"),
    CountryCode(code = "+356", country = "Malta"),
    CountryCode(code = "+692", country = "Marshall Islands"),
    CountryCode(code = "+596", country = "Martinique"),
    CountryCode(code = "+222", country = "Mauritania"),
    CountryCode(code = "+230", country = "Mauritius"),
    CountryCode(code = "+262269", country = "Mayotte"),
    CountryCode(code = "+262639", country = "Mayotte"),
    CountryCode(code = "+52", country = "Mexico"),
    CountryCode(code = "+691", country = "Micronesia, Federated States of"),
    CountryCode(code = "+1808", country = "Midway Island, USA"),
    CountryCode(code = "+373", country = "Moldova"),
    CountryCode(code = "+377", country = "Monaco"),
    CountryCode(code = "+976", country = "Mongolia"),
    CountryCode(code = "+382", country = "Montenegro"),
    CountryCode(code = "+1664", country = "Montserrat"),
    CountryCode(code = "+212", country = "Morocco"),
    CountryCode(code = "+258", country = "Mozambique"),
    CountryCode(code = "+95", country = "Myanmar"),
    CountryCode(code = "+37447", country = "Nagorno-Karabakh"),
    CountryCode(code = "+37497", country = "Nagorno-Karabakh"),
    CountryCode(code = "+264", country = "Namibia"),
    CountryCode(code = "+674", country = "Nauru"),
    CountryCode(code = "+977", country = "Nepal"),
    CountryCode(code = "+31", country = "Netherlands"),
    CountryCode(code = "+1869", country = "Nevis"),
    CountryCode(code = "+687", country = "New Caledonia"),
    CountryCode(code = "+64", country = "New Zealand"),
    CountryCode(code = "+505", country = "Nicaragua"),
    CountryCode(code = "+227", country = "Niger"),
    CountryCode(code = "+234", country = "Nigeria"),
    CountryCode(code = "+683", country = "Niue"),
    CountryCode(code = "+6723", country = "Norfolk Island"),
    CountryCode(code = "+389", country = "North Macedonia"),
    CountryCode(code = "+90392", country = "Northern Cyprus"),
    CountryCode(code = "+4428", country = "Northern Ireland"),
    CountryCode(code = "+1670", country = "Northern Mariana Islands"),
    CountryCode(code = "+47", country = "Norway"),
    CountryCode(code = "+968", country = "Oman"),
    CountryCode(code = "+92", country = "Pakistan"),
    CountryCode(code = "+680", country = "Palau"),
    CountryCode(code = "+970", country = "Palestine, State of"),
    CountryCode(code = "+507", country = "Panama"),
    CountryCode(code = "+675", country = "Papua New Guinea"),
    CountryCode(code = "+595", country = "Paraguay"),
    CountryCode(code = "+51", country = "Peru"),
    CountryCode(code = "+63", country = "Philippines"),
    CountryCode(code = "+64", country = "Pitcairn Islands"),
    CountryCode(code = "+48", country = "Poland"),
    CountryCode(code = "+351", country = "Portugal"),
    CountryCode(code = "+1787", country = "Puerto Rico"),
    CountryCode(code = "+1939", country = "Puerto Rico"),
    CountryCode(code = "+974", country = "Qatar"),
    CountryCode(code = "+262", country = "Réunion"),
    CountryCode(code = "+40", country = "Romania"),
    CountryCode(code = "+7", country = "Russia"),
    CountryCode(code = "+250", country = "Rwanda"),
    CountryCode(code = "+5994", country = "Saba"),
    CountryCode(code = "+590", country = "Saint Barthélemy"),
    CountryCode(code = "+290", country = "Saint Helena"),
    CountryCode(code = "+1869", country = "Saint Kitts and Nevis"),
    CountryCode(code = "+1758", country = "Saint Lucia"),
    CountryCode(code = "+590", country = "Saint Martin (France)"),
    CountryCode(code = "+508", country = "Saint Pierre and Miquelon"),
    CountryCode(code = "+1784", country = "Saint Vincent and the Grenadines"),
    CountryCode(code = "+685", country = "Samoa"),
    CountryCode(code = "+378", country = "San Marino"),
    CountryCode(code = "+239", country = "São Tomé and Príncipe"),
    CountryCode(code = "+966", country = "Saudi Arabia"),
    CountryCode(code = "+221", country = "Senegal"),
    CountryCode(code = "+381", country = "Serbia"),
    CountryCode(code = "+248", country = "Seychelles"),
    CountryCode(code = "+232", country = "Sierra Leone"),
    CountryCode(code = "+65", country = "Singapore"),
    CountryCode(code = "+5993", country = "Sint Eustatius"),
    CountryCode(code = "+1721", country = "Sint Maarten (Netherlands)"),
    CountryCode(code = "+421", country = "Slovakia"),
    CountryCode(code = "+386", country = "Slovenia"),
    CountryCode(code = "+677", country = "Solomon Islands"),
    CountryCode(code = "+252", country = "Somalia"),
    CountryCode(code = "+27", country = "South Africa"),
    CountryCode(code = "+500", country = "South Georgia and the South Sandwich Islands"),
    CountryCode(code = "+99534", country = "South Ossetia"),
    CountryCode(code = "+211", country = "South Sudan"),
    CountryCode(code = "+34", country = "Spain"),
    CountryCode(code = "+94", country = "Sri Lanka"),
    CountryCode(code = "+249", country = "Sudan"),
    CountryCode(code = "+597", country = "Suriname"),
    CountryCode(code = "+4779", country = "Svalbard"),
    CountryCode(code = "+46", country = "Sweden"),
    CountryCode(code = "+41", country = "Switzerland"),
    CountryCode(code = "+963", country = "Syria"),
    CountryCode(code = "+886", country = "Taiwan"),
    CountryCode(code = "+992", country = "Tajikistan"),
    CountryCode(code = "+255", country = "Tanzania"),
    CountryCode(code = "+888", country = "Telecommunications for Disaster Relief by OCHA"),
    CountryCode(code = "+66", country = "Thailand"),
    CountryCode(code = "+88216", country = "Thuraya (Mobile Satellite service)"),
    CountryCode(code = "+670", country = "East Timor"),
    CountryCode(code = "+228", country = "Togo"),
    CountryCode(code = "+690", country = "Tokelau"),
    CountryCode(code = "+676", country = "Tonga"),
    CountryCode(code = "+3732", country = "Transnistria"),
    CountryCode(code = "+3735", country = "Transnistria"),
    CountryCode(code = "+1868", country = "Trinidad and Tobago"),
    CountryCode(code = "+2908", country = "Tristan da Cunha"),
    CountryCode(code = "+216", country = "Tunisia"),
    CountryCode(code = "+90", country = "Turkey"),
    CountryCode(code = "+993", country = "Turkmenistan"),
    CountryCode(code = "+1649", country = "Turks and Caicos Islands"),
    CountryCode(code = "+688", country = "Tuvalu"),
    CountryCode(code = "+256", country = "Uganda"),
    CountryCode(code = "+380", country = "Ukraine"),
    CountryCode(code = "+971", country = "United Arab Emirates"),
    CountryCode(code = "+44", country = "United Kingdom"),
    CountryCode(code = "+1", country = "United States"),
    CountryCode(code = "+878", country = "Universal Personal Telecommunications (UPT)"),
    CountryCode(code = "+598", country = "Uruguay"),
    CountryCode(code = "+1340", country = "US Virgin Islands"),
    CountryCode(code = "+998", country = "Uzbekistan"),
    CountryCode(code = "+678", country = "Vanuatu"),
    CountryCode(code = "+3906698", country = "Vatican City State (Holy See)"),
    CountryCode(code = "+379", country = "Vatican City State (Holy See)"),
    CountryCode(code = "+58", country = "Venezuela"),
    CountryCode(code = "+84", country = "Vietnam"),
    CountryCode(code = "+1808", country = "Wake Island, USA"),
    CountryCode(code = "+681", country = "Wallis and Futuna"),
    CountryCode(code = "+967", country = "Yemen"),
    CountryCode(code = "+260", country = "Zambia"),
    CountryCode(code = "+25524", country = "Zanzibar"),
    CountryCode(code = "+263", country = "Zimbabwe")
)
